export const recomendations: Record<string, string> = {
    "0": "Welcome to life! Every week is a new opportunity to explore and grow.",
    "52": "You're one year old! Cherish the love and warmth of your family.",
    "156": "Enjoy the wonder of discovering new things every day.",
    "260": "You're 5 years old now! Play, learn, and enjoy the simple joys of childhood.",
    "364": "Be curious and ask questions about everything around you.",
    "520": "You're 10! Stay curious and keep dreaming big.",
    "676": "Friendships formed now can last a lifetime—choose them wisely.",
    "780": "Teen years are here! Explore your passions and nurture your friendships.",
    "936": "Make memories with your friends—adventures today become cherished stories tomorrow.",
    "1040": "You're stepping into adulthood. Enjoy the freedom, but don't forget your roots.",
    "1196": "Embrace challenges—they help you grow stronger and wiser.",
    "1300": "Time to chase your dreams! Travel, explore, and embrace every new experience.",
    "1456": "Don’t be afraid to take risks and step out of your comfort zone.",
    "1560": "Career may be picking up, but remember to make time for your friends and family.",
    "1716": "Life is not just about work—create space for what makes you happy.",
    "1820": "In the pursuit of success, don't lose sight of the little joys that make life beautiful.",
    "1976": "Small acts of kindness can have a big impact on those around you.",
    "2080": "Stay close to your loved ones. They are your greatest support system.",
    "2236": "Make time to call your parents and check in on old friends.",
    "2340": "Balance is key. Work hard, but don't forget to take care of yourself.",
    "2496": "Take time to travel and experience new perspectives.",
    "2600": "Your family and health are your most precious assets. Prioritize them.",
    "2756": "Reflect on your achievements and continue striving for your dreams.",
    "2860": "Life is moving fast—slow down and savor every moment.",
    "3016": "Cherish quality time with your family; their presence is invaluable.",
    "3120": "Time to pass on wisdom and cherish the bonds you've built.",
    "3276": "Reconnect with old passions and hobbies you once loved.",
    "3380": "Reignite old passions and reconnect with long-lost friends.",
    "3536": "Your experience is valuable—mentor and inspire younger generations.",
    "3640": "Your presence means the world to your loved ones. Stay close.",
    "3796": "Reflect on the journey you've had, and find joy in every memory.",
    "3900": "Reflect on the beautiful moments you've collected over the years.",
    "4056": "Share your wisdom and experiences with those around you.",
    "4160": "Time is the most valuable gift—spend it with those who matter most.",
    "4316": "Stay active and keep your mind engaged with new challenges.",
    "4420": "Celebrate life’s little victories and cherish the people around you.",
    "4576": "Enjoy the present moment—there's beauty in simplicity.",
    "4680": "Share your stories, inspire others, and leave a lasting impact.",
    "4836": "Enjoy the simple pleasures—watch the sunrise, listen to music, and laugh often.",
    "4940": "Stay active, stay curious, and keep embracing life with open arms.",
    "5096": "Embrace the joy in everyday moments and cherish loved ones.",
    "5200": "Your legacy is built on love and kindness. Continue to spread it.",
    "5356": "Each day is a gift—make the most of it with gratitude."
}
